use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/NoNameOrganazation/LNSpec.git'
platform :ios, '9.0'

target 'LNModuleCore_Example' do
  pod 'LNModuleCore', :path => '../'
  pod 'LNModuleProtocol'
  target 'LNModuleCore_Tests' do
    inherit! :search_paths
  end
end

target 'ModuleA' do
  pod 'LNModuleCore', :path => '../'
  pod 'LNModuleProtocol'
end

target 'ModuleB' do
  pod 'LNModuleCore', :path => '../'
  pod 'LNModuleProtocol'
end
